import react, { useState, useEffect } from "react";
import { AiOutlineClose, AiOutlineMenu } from "react-icons/ai";
import Image from "next/image";
import Head from "next/head";
import laptop from "../public/laptop.jpg";
import single from "../public/single.png";
import triple from "../public/triple.png";
import double from "../public/double.png";
import {
  FaDribbbleSquare,
  FaFacebookSquare,
  FaGithubSquare,
  FaInstagram,
  FaTwitterSquare,
} from 'react-icons/fa';




function useTypewriter(phrases, typingDelay, erasingDelay, pauseDelay) {
  const [currentPhraseIndex, setCurrentPhraseIndex] = useState(0);
  const [currentTypingText, setCurrentTypingText] = useState("");
  const [isErasing, setIsErasing] = useState(false); // New state to track erasing

  useEffect(() => {
    let isMounted = true;
    let timeout;

    const type = () => {
      if (!isMounted) return;

      if (!isErasing) {
        if (currentTypingText.length < phrases[currentPhraseIndex].length) {
          setCurrentTypingText((prevText) =>
            phrases[currentPhraseIndex].substring(0, prevText.length + 1)
          );
          timeout = setTimeout(type, typingDelay);
        } else {
          setIsErasing(true); // Transition to erasing state
          timeout = setTimeout(() => {
            setIsErasing(false); // Transition back to typing state
            erase();
          }, pauseDelay);
        }
      } else {
        erase();
      }
    };

    const erase = () => {
      if (!isMounted) return;

      if (currentTypingText.length > 0) {
        setCurrentTypingText((prevText) =>
          prevText.substring(0, prevText.length - 1)
        );
        timeout = setTimeout(erase, erasingDelay);
      } else {
        const nextIndex = (currentPhraseIndex + 1) % phrases.length;
        setCurrentPhraseIndex(nextIndex);
        setIsErasing(false); // Reset erasing state
        timeout = setTimeout(type, typingDelay);
      }
    };

    timeout = setTimeout(type, typingDelay);

    return () => {
      clearTimeout(timeout);
      isMounted = false;
    };
  }, [currentPhraseIndex, currentTypingText, phrases, typingDelay, erasingDelay, pauseDelay, isErasing]);

  return currentTypingText;
}
export default function TypewriterEffect() {
  const phrases = ["BTB", "BTC", "SASS"];
  const typingDelay = 200;
  const erasingDelay = 100;
  const pauseDelay = 5000;

  const currentTypingText = useTypewriter(phrases, typingDelay, erasingDelay, pauseDelay);

  

  
  const [nav, setNav] = useState(false);

  const handleNav = () => {
    setNav(!nav);
  };

  return (
    <div>
      <Head>
        <title>Envision Data Finance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Nav */}
        <div className="flex justify-between items-center h-24 max-w-[1240px] mx-auto px-4 text-white">
          <h1 className="w-full text-2xl font-bold text-green-300">ENVISION.</h1>
          <ul className="hidden md:flex">
          <a href="#"><li className="p-4">Home</li></a>
            <a href="#"><li className="p-4">Company</li></a>
            <a href="#"><li className="p-4">Resources</li></a>
            <a href="#"><li className="p-4">About</li></a>
            <a href="#"><li className="p-4">Contact</li></a>
          </ul>
          <div onClick={handleNav} className="block">
            {nav ? <AiOutlineMenu size={20} /> : <AiOutlineClose  size={20} />}
          </div>
          <div className={!nav ? "fixed left-0 top-0 w-[60%] h-full border-r border-r-gray-900 bg-[#000300] ease-in-out duration-500" : 'ease-in-out duration-500 fixed left-[-100%]'}>
            <h1 className="w-full text-2xl font-bold text-green-300 m-4">ENVISION.</h1>
            <ul className="uppercase p-4">
              <a href="#"><li className="p-4 border-b border-gray-600">Home</li></a>
              <a href="#"><li className="p-4 border-b border-gray-600">Company</li></a>
              <a href="#"><li className="p-4 border-b border-gray-600">Resources</li></a>
              <a href="#"><li className="p-4 border-b border-gray-600">About</li></a>
              <a href="#"><li className="p-4">Contact</li></a>
            </ul>
          </div>
        </div>
        {/* Hero */}
        <div className="text-white">
          <div className="maxw-[800px] mt-[-96px] w-full h-screen mx-auto text-center flex flex-col justify-center">
          <p className='text-[#00df9a] font-bold p-2'>
          GROWING WITH DATA ANALYTICS
        </p>
        <h1 className='md:text-7xl sm:text-6xl text-4xl font-bold md:py-6'>
          Grow with data.
        </h1>
        <div className="flex justify-center items-center">
          <p className='md:text-5xl sm:text-4xl text-xl font-bold py-4'>Fast, flexible, financing for{" "}
            <span className="text-[#00df9a]">{currentTypingText}</span></p>
       
        </div>
        <p className='md:text-2xl text-xl font-bold text-gray-500'>Monitor your data analytics to increase revenue for BTB, BTC, & SASS platforms.</p>
        <button className='bg-[#00df9a] w-[200px] rounded-md font-medium my-6 mx-auto py-3 text-black'>Get Started</button>
          </div>
        </div>
        {/* Analytics Dashboard */}
        <div className='w-full bg-white py-16 px-4'>
      <div className='max-w-[1240px] mx-auto grid md:grid-cols-2'>
      <div className='relative w-[500px] mx-auto my-4 hover-up-down'>
        <Image  alt="laptop" src={laptop} className='w-[500px] mx-auto my-4'   />
        </div>
        <div className='flex flex-col justify-center'>
          <p className='text-[#00df9a] font-bold '>DATA ANALYTICS DASHBOARD</p>
          <h1 className='md:text-4xl sm:text-3xl text-2xl font-bold py-2 text-black'>Manage Data Analytics Centrally</h1>
          <p className="text-black">
          Rich datasets and unmatched AI technology are employed to power the accuracy of our scalable, real-time credit decisioning systems.
          </p>
          <button className='bg-black text-[#00df9a] w-[200px] rounded-md font-medium my-6 mx-auto md:mx-0 py-3'>Get Started</button>
        </div>
      </div>
    </div>
    {/* Newsletter */}
    <div className='w-full py-16 text-white px-4'>
      <div className='max-w-[1240px] mx-auto grid lg:grid-cols-3'>
        <div className='lg:col-span-2 my-4'>
          <h1 className='md:text-4xl sm:text-3xl text-2xl font-bold py-2'>
            Want tips & tricks to optimize your flow?
          </h1>
          <p>Sign up to our newsletter and stay up to date.</p>
        </div>
        <div className='my-4'>
          <div className='flex flex-col sm:flex-row items-center justify-between w-full'>
            <input
              className='p-3 flex w-full rounded-md text-black'
              type='email'
              placeholder='Enter Email'
            />
            <button className='bg-[#00df9a] text-black rounded-md font-medium w-[200px] ml-4 my-6 px-6 py-3'>
              Notify Me
            </button>
          </div>
          <p>
            We care about the protection of your data. Read our{' '}
            <a href="#"><span className='text-[#00df9a]'>Privacy Policy.</span></a>
          </p>
        </div>
      </div>
    </div>
    {/* Purchase Packages */}
    <div className='w-full py-[10rem] px-4 bg-white'>
      <div className='max-w-[1240px] mx-auto grid md:grid-cols-3 gap-8'>
          <div className='w-full shadow-xl flex flex-col p-4 my-4 rounded-lg hover:scale-105 duration-300'>
              <Image className='w-20 mx-auto mt-[-3rem] bg-white' src={single} alt="/" />
              <h2 className='text-2xl font-bold text-center py-8 text-black'>Single User</h2>
              <p className='text-center text-4xl font-bold text-black'>$349</p>
              <div className='text-center font-medium'>
                  <p className='py-2 border-b mx-8 mt-8 text-black'>500 GB Storage</p>
                  <p className='py-2 border-b mx-8 text-black'>1 Granted User</p>
                  <p className='py-2 border-b mx-8 text-black'>Send up to 2 GB</p>
              </div>
              <button className='bg-[#00df9a] w-[200px] rounded-md font-medium my-6 mx-auto px-6 py-3'>Start 7 Day Free Trial</button>
          </div>
          <div className='w-full shadow-xl bg-gray-100 flex flex-col p-4 md:my-0 my-8 rounded-lg hover:scale-105 duration-300'>
              <Image className='w-20 mx-auto mt-[-3rem] bg-transparent' src={double} alt="/" />
              <h2 className='text-2xl font-bold text-center py-8 text-black'>Partnership</h2>
              <p className='text-center text-4xl font-bold text-black'>$550</p>
              <div className='text-center font-medium'>
                  <p className='py-2 border-b mx-8 mt-8 text-black'>1500 GB Storage</p>
                  <p className='py-2 border-b mx-8 text-black'>2 Granted Users</p>
                  <p className='py-2 border-b mx-8 text-black'>Send up to 10 GB</p>
              </div>
              <button className='bg-black text-[#00df9a] w-[200px] rounded-md font-medium my-6 mx-auto px-6 py-3'>Start 7 Day Free Trial</button>
          </div>
          <div className='w-full shadow-xl flex flex-col p-4 my-4 rounded-lg hover:scale-105 duration-300'>
              <Image className='w-20 mx-auto mt-[-3rem] bg-white' src={triple} alt="/" />
              <h2 className='text-2xl font-bold text-center py-8 text-black'>Group Account</h2>
              <p className='text-center text-4xl font-bold text-black'>$1049</p>
              <div className='text-center font-medium'>
                  <p className='py-2 border-b mx-8 mt-8 text-black'>5000 GB Storage</p>
                  <p className='py-2 border-b mx-8 text-black'>3+ Granted Users</p>
                  <p className='py-2 border-b mx-8 text-black'>Send up to 50 GB</p>
              </div>
              <button className='bg-[#00df9a] w-[200px] rounded-md font-medium my-6 mx-auto px-6 py-3'>Start 7 Day Free Trial</button>
          </div>
      </div>
    </div>
    {/* Footer */}
    <div className='max-w-[1240px] mx-auto py-16 px-4 grid lg:grid-cols-3 gap-8 text-gray-300'>
      <div>
        <h1 className='w-full text-3xl font-bold text-[#00df9a]'>ENVISON.</h1>
        <p className='py-4'>Stay connected with us on social media or click these links to explore what makes us the top data financing company of 2023.</p>
        <div className='flex justify-between md:w-[75%] my-6'>
        <a href="#"><FaFacebookSquare size={30} /></a>
        <a href="#"><FaInstagram size={30} /></a>
        <a href="#"><FaTwitterSquare size={30} /></a>
        <a href="#"><FaGithubSquare size={30} /></a>
        <a href="#"><FaDribbbleSquare size={30} /></a>
        </div>
      </div>
      <div className='lg:col-span-2 flex justify-between mt-6'>
    <div>
        <a href="#"><h6 className='font-medium text-[#00df9a]'>Solutions</h6></a>
        <ul>
        <a href="#"><li className='py-2 text-sm'>Analytics</li></a>
        <a href="#"><li className='py-2 text-sm'>Marketing</li></a>
        <a href="#"><li className='py-2 text-sm'>Commerce</li></a>
        <a href="#"><li className='py-2 text-sm'>Insights</li></a>
        </ul>
    </div>
    <div>
    <a href="#"><h6 className='font-medium text-[#00df9a]'>Support</h6></a>
        <ul>
        <a href="#"><li className='py-2 text-sm'>Pricing</li></a>
        <a href="#"><li className='py-2 text-sm'>Documentation</li></a>
        <a href="#"><li className='py-2 text-sm'>Guides</li></a>
        <a href="#"><li className='py-2 text-sm'>API Status</li></a>
        </ul>
    </div>
    <div>
    <a href="#"><h6 className='font-medium text-[#00df9a]'>Company</h6></a>
        <ul>
        <a href="#"><li className='py-2 text-sm'>About</li></a>
        <a href="#"><li className='py-2 text-sm'>Blog</li></a>
        <a href="#"><li className='py-2 text-sm'>Jobs</li></a>
        <a href="#"><li className='py-2 text-sm'>Press</li></a>
        <a href="#"><li className='py-2 text-sm'>Careers</li></a>
        </ul>
    </div>
    <div>
    <a href="#"><h6 className='font-medium text-[#00df9a]'>Legal</h6></a>
        <ul>
        <a href="#"><li className='py-2 text-sm'>Claim</li></a>
        <a href="#"><li className='py-2 text-sm'>Policy</li></a>
        <a href="#"><li className='py-2 text-sm'>Terms</li></a>
        </ul>
    </div>
      </div>
    </div>
      </main>
    </div>
    
  );
}

